import SwiftUI
import Foundation

struct CurrencyItem: Identifiable {
    let code: String
    var id: String { code }
    let name: String
}

let currencyItems: [CurrencyItem] = [
    CurrencyItem(code: "AED", name: "UAE Dirham"),
    CurrencyItem(code: "AFN", name: "Afghan Afghani"),
    CurrencyItem(code: "ALL", name: "Albanian Lek"),
    CurrencyItem(code: "AMD", name: "Armenian Dram"),
    CurrencyItem(code: "ANG", name: "Netherlands Antillean Guilder"),
    CurrencyItem(code: "AOA", name: "Angolan Kwanza"),
    CurrencyItem(code: "ARS", name: "Argentine Peso"),
    CurrencyItem(code: "AUD", name: "Australian Dollar"),
    CurrencyItem(code: "AWG", name: "Aruban Florin"),
    CurrencyItem(code: "AZN", name: "Azerbaijani Manat"),
    CurrencyItem(code: "BAM", name: "Bosnia and Herzegovina Mark"),
    CurrencyItem(code: "BBD", name: "Barbados Dollar"),
    CurrencyItem(code: "BDT", name: "Bangladeshi Taka"),
    CurrencyItem(code: "BGN", name: "Bulgarian Lev"),
    CurrencyItem(code: "BHD", name: "Bahraini Dinar"),
    CurrencyItem(code: "BIF", name: "Burundian Franc"),
    CurrencyItem(code: "BMD", name: "Bermudian Dollar"),
    CurrencyItem(code: "BND", name: "Brunei Dollar"),
    CurrencyItem(code: "BOB", name: "Bolivian Boliviano"),
    CurrencyItem(code: "BRL", name: "Brazilian Real"),
    CurrencyItem(code: "BSD", name: "Bahamian Dollar"),
    CurrencyItem(code: "BTN", name: "Bhutanese Ngultrum"),
    CurrencyItem(code: "BWP", name: "Botswana Pula"),
    CurrencyItem(code: "BYN", name: "Belarusian Ruble"),
    CurrencyItem(code: "BZD", name: "Belize Dollar"),
    CurrencyItem(code: "CAD", name: "Canadian Dollar"),
    CurrencyItem(code: "CDF", name: "Congolese Franc"),
    CurrencyItem(code: "CHF", name: "Swiss Franc"),
    CurrencyItem(code: "CLP", name: "Chilean Peso"),
    CurrencyItem(code: "CNY", name: "Chinese Renminbi"),
    CurrencyItem(code: "COP", name: "Colombian Peso"),
    CurrencyItem(code: "CRC", name: "Costa Rican Colon"),
    CurrencyItem(code: "CUP", name: "Cuban Peso"),
    CurrencyItem(code: "CVE", name: "Cape Verdean Escudo"),
    CurrencyItem(code: "CZK", name: "Czech Koruna"),
    CurrencyItem(code: "DJF", name: "Djiboutian Franc"),
    CurrencyItem(code: "DKK", name: "Danish Krone"),
    CurrencyItem(code: "DOP", name: "Dominican Peso"),
    CurrencyItem(code: "DZD", name: "Algerian Dinar"),
    CurrencyItem(code: "EGP", name: "Egyptian Pound"),
    CurrencyItem(code: "ERN", name: "Eritrean Nakfa"),
    CurrencyItem(code: "ETB", name: "Ethiopian Birr"),
    CurrencyItem(code: "EUR", name: "Euro"),
    CurrencyItem(code: "FJD", name: "Fiji Dollar"),
    CurrencyItem(code: "FKP", name: "Falkland Islands Pound"),
    CurrencyItem(code: "FOK", name: "Faroese Króna"),
    CurrencyItem(code: "GBP", name: "Pound Sterling"),
    CurrencyItem(code: "GEL", name: "Georgian Lari"),
    CurrencyItem(code: "GGP", name: "Guernsey Pound"),
    CurrencyItem(code: "GHS", name: "Ghanaian Cedi"),
    CurrencyItem(code: "GIP", name: "Gibraltar Pound"),
    CurrencyItem(code: "GMD", name: "Gambian Dalasi"),
    CurrencyItem(code: "GNF", name: "Guinean Franc"),
    CurrencyItem(code: "GTQ", name: "Guatemalan Quetzal"),
    CurrencyItem(code: "GYD", name: "Guyanese Dollar"),
    CurrencyItem(code: "HKD", name: "Hong Kong Dollar"),
    CurrencyItem(code: "HNL", name: "Honduran Lempira"),
    CurrencyItem(code: "HRK", name: "Croatian Kuna"),
    CurrencyItem(code: "HTG", name: "Haitian Gourde"),
    CurrencyItem(code: "HUF", name: "Hungarian Forint"),
    CurrencyItem(code: "IDR", name: "Indonesian Rupiah"),
    CurrencyItem(code: "ILS", name: "Israeli New Shekel"),
    CurrencyItem(code: "IMP", name: "Manx Pound"),
    CurrencyItem(code: "INR", name: "Indian Rupee"),
    CurrencyItem(code: "IQD", name: "Iraqi Dinar"),
    CurrencyItem(code: "IRR", name: "Iranian Rial"),
    CurrencyItem(code: "ISK", name: "Icelandic Króna"),
    CurrencyItem(code: "JEP", name: "Jersey Pound"),
    CurrencyItem(code: "JMD", name: "Jamaican Dollar"),
    CurrencyItem(code: "JOD", name: "Jordanian Dinar"),
    CurrencyItem(code: "JPY", name: "Japanese Yen"),
    CurrencyItem(code: "KES", name: "Kenyan Shilling"),
    CurrencyItem(code: "KGS", name: "Kyrgyzstani Som"),
    CurrencyItem(code: "KHR", name: "Cambodian Riel"),
    CurrencyItem(code: "KID", name: "Kiribati Dollar"),
    CurrencyItem(code: "KMF", name: "Comorian Franc"),
    CurrencyItem(code: "KRW", name: "South Korean Won"),
    CurrencyItem(code: "KWD", name: "Kuwaiti Dinar"),
    CurrencyItem(code: "KYD", name: "Cayman Islands Dollar"),
    CurrencyItem(code: "KZT", name: "Kazakhstani Tenge"),
    CurrencyItem(code: "LAK", name: "Lao Kip"),
    CurrencyItem(code: "LBP", name: "Lebanese Pound"),
    CurrencyItem(code: "LKR", name: "Sri Lanka Rupee"),
    CurrencyItem(code: "LRD", name: "Liberian Dollar"),
    CurrencyItem(code: "LSL", name: "Lesotho Loti"),
    CurrencyItem(code: "LYD", name: "Libyan Dinar"),
    CurrencyItem(code: "MAD", name: "Moroccan Dirham"),
    CurrencyItem(code: "MDL", name: "Moldovan Leu"),
    CurrencyItem(code: "MGA", name: "Malagasy Ariary"),
    CurrencyItem(code: "MKD", name: "Macedonian Denar"),
    CurrencyItem(code: "MMK", name: "Burmese Kyat"),
    CurrencyItem(code: "MNT", name: "Mongolian Tögrög"),
    CurrencyItem(code: "MOP", name: "Macanese Pataca"),
    CurrencyItem(code: "MRU", name: "Mauritanian Ouguiya"),
    CurrencyItem(code: "MUR", name: "Mauritian Rupee"),
    CurrencyItem(code: "MVR", name: "Maldivian Rufiyaa"),
    CurrencyItem(code: "MWK", name: "Malawian Kwacha"),
    CurrencyItem(code: "MXN", name: "Mexican Peso"),
    CurrencyItem(code: "MYR", name: "Malaysian Ringgit"),
    CurrencyItem(code: "MZN", name: "Mozambican Metical"),
    CurrencyItem(code: "NAD", name: "Namibian Dollar"),
    CurrencyItem(code: "NGN", name: "Nigerian Naira"),
    CurrencyItem(code: "NIO", name: "Nicaraguan Córdoba"),
    CurrencyItem(code: "NOK", name: "Norwegian Krone"),
    CurrencyItem(code: "NPR", name: "Nepalese Rupee"),
    CurrencyItem(code: "NZD", name: "New Zealand Dollar"),
    CurrencyItem(code: "OMR", name: "Omani Rial"),
    CurrencyItem(code: "PAB", name: "Panamanian Balboa"),
    CurrencyItem(code: "PEN", name: "Peruvian Sol"),
    CurrencyItem(code: "PGK", name: "Papua New Guinean Kina"),
    CurrencyItem(code: "PHP", name: "Philippine Peso"),
    CurrencyItem(code: "PKR", name: "Pakistani Rupee"),
    CurrencyItem(code: "PLN", name: "Polish Złoty"),
    CurrencyItem(code: "PYG", name: "Paraguayan Guaraní"),
    CurrencyItem(code: "QAR", name: "Qatari Riyal"),
    CurrencyItem(code: "RON", name: "Romanian Leu"),
    CurrencyItem(code: "RSD", name: "Serbian Dinar"),
    CurrencyItem(code: "RUB", name: "Russian Ruble"),
    CurrencyItem(code: "RWF", name: "Rwandan Franc"),
    CurrencyItem(code: "SAR", name: "Saudi Riyal"),
    CurrencyItem(code: "SBD", name: "Solomon Islands Dollar"),
    CurrencyItem(code: "SCR", name: "Seychellois Rupee"),
    CurrencyItem(code: "SDG", name: "Sudanese Pound"),
    CurrencyItem(code: "SEK", name: "Swedish Krona"),
    CurrencyItem(code: "SGD", name: "Singapore Dollar"),
    CurrencyItem(code: "SHP", name: "Saint Helena Pound"),
    CurrencyItem(code: "SLE", name: "Sierra Leonean Leone"),
    CurrencyItem(code: "SOS", name: "Somali Shilling"),
    CurrencyItem(code: "SRD", name: "Surinamese Dollar"),
    CurrencyItem(code: "SSP", name: "South Sudanese Pound"),
    CurrencyItem(code: "STN", name: "São Tomé and Príncipe Dobra"),
    CurrencyItem(code: "SYP", name: "Syrian Pound"),
    CurrencyItem(code: "SZL", name: "Swazi Lilangeni"),
    CurrencyItem(code: "THB", name: "Thai Baht"),
    CurrencyItem(code: "TJS", name: "Tajikistani Somoni"),
    CurrencyItem(code: "TMT", name: "Turkmenistan Manat"),
    CurrencyItem(code: "TND", name: "Tunisian Dinar"),
    CurrencyItem(code: "TOP", name: "Tongan Paʻanga"),
    CurrencyItem(code: "TRY", name: "Turkish Lira"),
    CurrencyItem(code: "TTD", name: "Trinidad and Tobago Dollar"),
    CurrencyItem(code: "TVD", name: "Tuvaluan Dollar"),
    CurrencyItem(code: "TWD", name: "New Taiwan Dollar"),
    CurrencyItem(code: "TZS", name: "Tanzanian Shilling"),
    CurrencyItem(code: "UAH", name: "Ukrainian Hryvnia"),
    CurrencyItem(code: "UGX", name: "Ugandan Shilling"),
    CurrencyItem(code: "USD", name: "United States Dollar"),
    CurrencyItem(code: "UYU", name: "Uruguayan Peso"),
    CurrencyItem(code: "UZS", name: "Uzbekistani Soʻm"),
    CurrencyItem(code: "VES", name: "Venezuelan Bolívar"),
    CurrencyItem(code: "VND", name: "Vietnamese Đồng"),
    CurrencyItem(code: "VUV", name: "Vanuatu Vatu"),
    CurrencyItem(code: "WST", name: "Samoan Tālā"),
    CurrencyItem(code: "XAF", name: "Central African CFA Franc"),
    CurrencyItem(code: "XCD", name: "East Caribbean Dollar"),
    CurrencyItem(code: "XDR", name: "Special Drawing Rights"),
    CurrencyItem(code: "XOF", name: "West African CFA franc"),
    CurrencyItem(code: "XPF", name: "CFP Franc"),
    CurrencyItem(code: "YER", name: "Yemeni Rial"),
    CurrencyItem(code: "ZAR", name: "South African Rand"),
    CurrencyItem(code: "ZMW", name: "Zambian Kwacha"),
    CurrencyItem(code: "ZWL", name: "Zimbabwean Dollar")
]

